### ISSUE TITLE
2 modules are not found: `llama_attn_replace` and `supervised_fine_tune_rel_extraction`

### ISSUE THREAD

**Issue by bienchudc** [OSU-NLP-Group/TableLlama#1]
These 2 modules are imported in `inference_rel_extraction_col_type.py` but your repo is not providing them. I also setup the environment following the instruction.
For `llama_attn_replace`, I found it in [LongLoRa repo](https://github.com/dvlab-research/LongLoRA/blob/main/llama_attn_replace.py) But I have no idea for `supervised_fine_tune_rel_extraction`.

**Comment by zhangtianshu** [comment]
Thanks for your correction! I have updated the repo and fixed the issues. Now you can find llama_attn_replace in the repo and "supervised_fine_tune_rel_extraction" should be "supervised_fine_tune".
