### ISSUE TITLE
Is there/Will there be a similar dataset in Simplified Chinese? I'm trying to reproduce the finetune procedure on some Chinese opensource LLMs.

### ISSUE THREAD

**Issue by nameless0704** [OSU-NLP-Group/TableLlama#2]
Or I assume the structure is the same so if I directly translate/project  the dataset into simplified Chinese and the pattern still works.

**Comment by zhangtianshu** [comment]
You can check this: https://github.com/SpursGoZmy/IM-TQA which provides a Chinese table QA dataset. I think the pattern will work if the base Chinese open-source LLMs are good.

**Comment by nameless0704** [comment]
> You can check this: https://github.com/SpursGoZmy/IM-TQA which provides a Chinese table QA dataset. I think the pattern will work if the base Chinese open-source LLMs are good.

Thank you so much for your reply.
