### ISSUE TITLE
fine-tuning time 

### ISSUE THREAD

**Issue by Haruka1307** [OSU-NLP-Group/TableLlama#3]
May I ask how long it took you to fine tune? I just use rel_extraction data and it takes me over 3 hours now...I use lora as well.

**Comment by Haruka1307** [comment]
I run it on 8×A800-SXM4-80GB

**Comment by zhangtianshu** [comment]
Relation extration is a relatively large dataset in our corpus. It takes around 9h without using lora on 8*A100 (80G)
