### ISSUE TITLE
Missing files for inference

### ISSUE THREAD

**Issue by giangnguyen2412** [OSU-NLP-Group/TableLlama#6]
Hi authors,

where can i get such files (e.g. /test_data/test_col_type.json) for inference? I could not fine them anywhere to run the inference.

Thanks!

**Comment by zhangtianshu** [comment]
Check this link https://huggingface.co/datasets/osunlp/TableInstruct/tree/main/eval_data/in_domain_test

**Comment by giangnguyen2412** [comment]
Thanks Tianshu!
